name: CI Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory:"coverage"
      
    - run: Move-Item .\coverage\**\coverage.cobertura.xml .\coverage\coverage.cobertura.xml
      shell: pwsh
      
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: cobertura.xml
