name: CI Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    
    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release
