name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Extract version from tag name
      uses: olegtarasov/get-tag@v2.1
      id: tagName
    
    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ steps.tagName.outputs.tag }} /p:FileVersion=${{ steps.tagName.outputs.tag }} /p:AssemblyVersion=${{ steps.tagName.outputs.tag }}
    
    - name: Test
      run: dotnet test --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.tagName.outputs.tag }} /p:Version=${{ steps.tagName.outputs.tag }} /p:FileVersion=${{ steps.tagName.outputs.tag }} /p:AssemblyVersion=${{ steps.tagName.outputs.tag }}

    - name: Push nuget package
      run: dotnet nuget push ./Changey/nupkg/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_KEY }} --no-symbols true -s https://api.nuget.org/v3/index.json
      
    - name: Extract changelog
      run: dotnet Changey/bin/Release/netcoreapp5.0/Changey.dll extract ${{ steps.tagName.outputs.tag }} -t Changey/nupkg/changelog.md
      
    - name: Create github release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "Changey/nupkg/*.nupkg"
        bodyFile: "Changey/nupkg/changelog.md"
